repositories:
  - name: actions-runner-controller
    url: https://actions-runner-controller.github.io/actions-runner-controller

releases:
  - namespace: actions
    name: actions-runner-controller
    chart: actions-runner-controller/actions-runner-controller
    values:
      - "./values.yaml"
    hooks:
      - events: [ "prepare" ]
        showlogs: true
        command: "kubectl"
        args: [ "create", "namespace", "actions" ]